version: '3'

services:
  config_daemon:
    build:
      context: .
      dockerfile: config_daemon/Dockerfile
    volumes:
      - ./configs:/configs
    ports:
      - "51820:51820/udp"
    networks:
      my_network:
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    environment:
      - HOSTNAME=jit.pythonplayer123.dev

  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./configs:/home/runner
    networks:
      my_network:


  sidejitserver:
    build:
      context: .
      dockerfile: sidejitserver/Dockerfile
    ports:
      - "6969:8080"
      - "49151:49151"
    volumes:
      - ./configs/.pymobiledevice3:/root/.pymobiledevice3

    networks:
      my_network:
#        ipv6_address: fd69:420:4ece::69
        ipv4_address: 10.10.9.2
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      my_network:

networks:
  my_network:
    # Set IPv6 subnet for use
    # Don't modify gateway
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
#        - subnet: fd69:420:4ece::/48
        - subnet: 10.10.9.0/24
