version: '3'

services:
  config_daemon:
    build:
      context: .
      dockerfile: config_daemon/Dockerfile
    volumes:
      - ./configs:/configs
      - ./configs:/home/runner
      - /lib/modules:/lib/modules
    #ports:
    #  - "51820:51820/udp"
    networks:
      my_network:
        ipv4_address: 10.9.9.69

    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    environment:
      - HOSTNAME=jit.pythonplayer123.dev
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./configs:/home/runner
    networks:
      my_network:


#   sidejitserver:
#     build:
#       context: .
#       dockerfile: sidejitserver/Dockerfile
#     ports:
#       - "6969:8080"
#       - "49151:49151"
#     volumes:
#       - ./configs/.pymobiledevice3:/root/.pymobiledevice3

#     networks:
#       my_network:
# #        ipv6_address: fd69:420:4ece::69
#         ipv4_address: 10.9.9.69
#     cap_add:
#       - NET_ADMIN
#       - NET_RAW

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      my_network:
        ipv4_address: 10.9.9.70

networks:
  my_network:
    # Set IPv6 subnet for use
    # Don't modify gateway
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
#        - subnet: fd69:420:4ece::/48
        - subnet: 10.9.0.0/16
